import type { Metadata } from "next";
import { Bpmf_Huninn } from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

const bpmfHuninn = Bpmf_Huninn({
  src: [
    {
      path: "../../public/fonts/bpmf-huninn-v6-latin-regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-bpmf-huninn",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(bpmfHuninn.variable, "dark", "h-full", "antialiased", "font-sans")}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
